<?php
/**
 * Dc_Decidir
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Dc
 * @package    Dc_Decidir
 * @copyright  Copyright (c) 2015 Damián Culotta. (http://www.damianculotta.com.ar/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<p><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
    <tbody>
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <tr>
            <th><strong><?php echo $this->escapeHtml($_label)?>:</strong></th>
        </tr>
        <tr>
            <td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif;?>

<?php echo $this->getChildHtml()?>
